# Generated by Django 4.0.4 on 2022-04-20 21:05

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description1', models.CharField(max_length=250, verbose_name='Açıklama 1')),
                ('description2', models.CharField(max_length=250, verbose_name='Açıklama 2')),
                ('imageURL1', models.ImageField(upload_to='', verbose_name='Resim 1')),
                ('imageURL2', models.ImageField(upload_to='', verbose_name='Resim 2')),
            ],
        ),
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSurname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ad-Soyad')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('status', models.BooleanField(blank=True, default=True, null=True, verbose_name='Durum')),
                ('imageURL', models.ImageField(upload_to='', verbose_name='Resim')),
                ('about', models.TextField(blank=True, max_length=250, null=True, verbose_name='Yazar Biyografisi')),
                ('username', models.CharField(max_length=30, verbose_name='Kullanıcı Adı')),
                ('password', models.CharField(max_length=30, verbose_name='Şifre')),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Başlık')),
                ('description', ckeditor.fields.RichTextField(null=True, verbose_name='Açıklama')),
                ('fileURL', models.FileField(blank=True, null=True, upload_to='blog', verbose_name='Dosya')),
                ('release_date', models.DateField(auto_now_add=True, null=True, verbose_name='Yayınlanma Tarihi')),
                ('status', models.BooleanField(blank=True, default=True, null=True, verbose_name='Durum')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique=True)),
                ('authors', models.ManyToManyField(related_name='blogAuthor', to='blogapp.author')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('description', ckeditor.fields.RichTextField(max_length=500, verbose_name='Kategori Detayı')),
                ('status', models.BooleanField(blank=True, default=True, verbose_name='Durum')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ortak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorX', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.author')),
                ('blogY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.blog')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSurname', models.CharField(max_length=50, verbose_name='Ad-Soyad')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('message', models.CharField(max_length=500, verbose_name='Mesaj')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True, verbose_name='Durum')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogapp.blog')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogapp.category'),
        ),
        migrations.AddField(
            model_name='author',
            name='blogs',
            field=models.ManyToManyField(related_name='authorBlog', to='blogapp.blog'),
        ),
    ]
